LeftLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 1e-05
  kinematics_solver_timeout: 0.01
RightLeg:
  kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 1e-05
  kinematics_solver_timeout: 0.01