!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  double_support_ratio: 0.05
  first_step_swing_factor: 1.0
  first_step_trunk_phase: 0.0
  foot_apex_phase: 0.5
  foot_distance: 0.13
  foot_overshoot_phase: 0.85
  foot_overshoot_ratio: 0.1
  foot_put_down_phase: 1.0
  foot_put_down_roll_offset: 0.0
  foot_put_down_z_offset: 0.0
  foot_rise: 0.04
  foot_z_pause: 0.0
  freq: 1.5190000000000001
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          additional: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              foot_apex_phase: 0.5
              foot_overshoot_phase: 0.85
              foot_overshoot_ratio: 0.1
              foot_put_down_phase: 1.0
              foot_put_down_z_offset: 0.0
              foot_z_pause: 0.0
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              name: additional
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              trunk_pause: 0.0
              trunk_pitch_p_coef_turn: 0.0
              trunk_x_offset: 0.0
              trunk_x_offset_p_coef_forward: 0.0
              trunk_x_offset_p_coef_turn: 0.0
              trunk_y_offset: 0.0
              type: ''
            state: []
          engine_main: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              double_support_ratio: 0.05
              foot_distance: 0.13
              foot_rise: 0.04
              freq: 1.5190000000000001
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              l_sole_frame: l_sole
              name: engine_main
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              r_sole_frame: r_sole
              state: true
              trunk_height: 0.35
              trunk_phase: 0.0
              trunk_pitch: 0.0
              trunk_pitch_p_coef_forward: 0.0
              trunk_swing: 0.6
              type: ''
            state: []
          experimental: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              first_step_swing_factor: 1.0
              first_step_trunk_phase: 0.0
              foot_put_down_roll_offset: 0.0
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              name: experimental
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              trunk_z_movement: 0.0
              type: ''
            state: []
          kick: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              kick_length: 0.09
              kick_phase: 0.75
              kick_vel: 0.2
              name: kick
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  kick_length: 0.09
  kick_phase: 0.75
  kick_vel: 0.2
  l_sole_frame: l_sole
  r_sole_frame: r_sole
  trunk_height: 0.35
  trunk_pause: 0.0
  trunk_phase: 0.0
  trunk_pitch: 0.0
  trunk_pitch_p_coef_forward: 0.0
  trunk_pitch_p_coef_turn: 0.0
  trunk_swing: 0.6
  trunk_x_offset: 0.0
  trunk_x_offset_p_coef_forward: 0.0
  trunk_x_offset_p_coef_turn: 0.0
  trunk_y_offset: 0.0
  trunk_z_movement: 0.0
state: []
